name: insightviewer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  fl_chart: ^1.0.0
  intl: ^0.20.2
  country_icons: ^3.0.0
  web_socket_channel: ^3.0.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/icon/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  background_color: "#FF0000"
  adaptive_icon_background: "#FF0000"
  remove_alpha_ios: true